### ISSUE TITLE
Plugin may not be compatible with your version of NodeBB

### ISSUE THREAD

**Issue by tbeitter** [dovydaskukalis/nodebb-plugin-twitter#10]
The plugin still works with NodeBB v1.1.2 but the following warning shows up with every restart:

```
The following plugins may not be compatible with your version of NodeBB.

warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-twitter
```

**Comment by tbeitter** [comment]
it stopped working, don't know exactely with which version, v1.4.3 is online right now.

**Comment by sosojni** [comment]
It works for me on 1.7.2 but it does give warning.
Im guessing it's because compatibility needs to be updated in package.json
Currently sais: 
"nbbpm": {
	"compatibility": "^0.7.0"
},

**Comment by dovydaskukalis** [comment]
Please use new version from https://github.com/nodebb-community/nodebb-plugin-twitter.
