### ISSUE TITLE
Support for redactor plugin?

### ISSUE THREAD

**Issue by codecowboy** [dovydaskukalis/nodebb-plugin-twitter#8]
I tried installing this and get:

npm install nodebb-plugin-twitter
npm ERR! Linux 2.6.32-042stab108.5
npm ERR! argv "node" "/usr/bin/npm" "install" "nodebb-plugin-twitter"
npm ERR! node v0.10.36
npm ERR! npm  v2.14.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package nodebb-plugin-composer-default@1.0.20 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nodebb-plugin-composer-redactor@1.3.6 wants nodebb-plugin-composer-default@>=1.0.24

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/vhosts/xxxx.com/xxxx.xxxxx.com/nodebb/npm-debug.log

I am using the redactor composer plugin as it has support for embedding videos etc. NodeBB version is 0.90

**Comment by codecowboy** [comment]
@dovydaskukalis  can you please explain why you have closed this issue?

**Comment by dovydaskukalis** [comment]
Hi

I am not even sure how it's related to the plugin as the plugin doesn't have any dependency requirements. Reading the error, it looks like you might need to update nodebb-plugin-composer-default.
